//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotPartsSynthesis.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotPartsSynthesis.Properties.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   画像の破棄処理に失敗しました。値：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Debug_DotImage_FailedDisposeImage {
            get {
                return ResourceManager.GetString("Debug_DotImage_FailedDisposeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App.configのdotoPartsDirsには2つ以上の存在するフォルダを設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_AppConfig_DotPartsDirsUnder2 {
            get {
                return ResourceManager.GetString("Error_AppConfig_DotPartsDirsUnder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App.configのdotPartsDirsを設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_AppConfig_NullDotPartsDirs {
            get {
                return ResourceManager.GetString("Error_AppConfig_NullDotPartsDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App.configのexportDirを設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_AppConfig_NullExportDir {
            get {
                return ResourceManager.GetString("Error_AppConfig_NullExportDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   組み合わせリストの中には値の入ったリストを2つ以上設定してください。値：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_BruteForceManager_ListSizeUnder2 {
            get {
                return ResourceManager.GetString("Error_BruteForceManager_ListSizeUnder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   組み合わせリストを設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_BruteForceManager_NullList {
            get {
                return ResourceManager.GetString("Error_BruteForceManager_NullList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カウンターの最大値は0以上を設定してください。値：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_Counter_MaxCountUnder0 {
            get {
                return ResourceManager.GetString("Error_Counter_MaxCountUnder0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カウンターの最大値を指定するリストは要素数2以上の配列を指定してください。値：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_CounterManager_ListSizeUnder2 {
            get {
                return ResourceManager.GetString("Error_CounterManager_ListSizeUnder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カウンターの最大値を指定するリストを設定してください。値：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_CounterManager_NullListSize {
            get {
                return ResourceManager.GetString("Error_CounterManager_NullListSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドット絵のパスを指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_DotImage_NullFile {
            get {
                return ResourceManager.GetString("Error_DotImage_NullFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像の合成に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_DotImageService_FailedSynthesis {
            get {
                return ResourceManager.GetString("Error_DotImageService_FailedSynthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像を書き込みます。ファイル：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_DotImage_WriteDotImage {
            get {
                return ResourceManager.GetString("Info_DotImage_WriteDotImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力フォルダを作成します。値：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_DotImageService_CreateExportDir {
            get {
                return ResourceManager.GetString("Info_DotImageService_CreateExportDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像の合成を開始します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_DotImageService_ExecuteSynthesis {
            get {
                return ResourceManager.GetString("Info_DotImageService_ExecuteSynthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像の読み込みが完了しました。画像数：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_DotImageService_ReadedDotImages {
            get {
                return ResourceManager.GetString("Info_DotImageService_ReadedDotImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像の読み込みを開始します。{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_DotImageService_ReadingDotImages {
            get {
                return ResourceManager.GetString("Info_DotImageService_ReadingDotImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像の合成が成功しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_DotImageService_SuccessSynthesis {
            get {
                return ResourceManager.GetString("Info_DotImageService_SuccessSynthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像の合成を開始します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_DotImageService_SynthesisDotImage {
            get {
                return ResourceManager.GetString("Info_DotImageService_SynthesisDotImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像の合成を開始します。ファイル1：{0}　ファイル2：{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_DotImageSynthesis_ExecuteSynthesis {
            get {
                return ResourceManager.GetString("Info_DotImageSynthesis_ExecuteSynthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドット絵パーツフォルダが存在しません。値：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Warn_AppConfig_NotExistsDotPartsDir {
            get {
                return ResourceManager.GetString("Warn_AppConfig_NotExistsDotPartsDir", resourceCulture);
            }
        }
    }
}
